### ISSUE TITLE
Make UNUSED a more compact representation

### ISSUE THREAD

**Issue by kjnilsson** [k32/map_sets#6]
Would it make sense to make the unused value either an empty binary, empty list or the empty atom `''` so to reduce it's overhead when serialized using `term_to_binary/1`?

**Comment by k32** [comment]
Makes sense.

**Comment by k32** [comment]
Initially the idea of using `unused` atom was to make representation more human friendly, but the figures talk for themselves:

```
2> size(term_to_binary([])).
2
3> size(term_to_binary(<<>>)).
6
4> size(term_to_binary('')).  
4
5> size(term_to_binary(unused)).  
10
```
Empty list looks like a clear winner, I will use it. Thanks for suggestion!
